language: node_js
node_js:
- 6.2.0
script: "./bin/test.sh"
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token: 060bbed9058dfe2a159b713fc859106ee73b42abd4155756d805a23c4b0b7722
